# Generated by Django 6.0.7 on 2026-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
